# Build script
init:
  - git config --global core.autocrlf true

image: 
  - Visual Studio 2017
  
# Build script
build_script:
  - ps: .\build.ps1 -Target "Default" -Configuration "Release"

# Tests
test: off

# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts\*

deploy:
- provider: NuGet
  server: https://www.myget.org/F/frozenskys/api/v2/package
  api_key:
    secure: CCRJd2JR9N5auUK9y4bu134vWE8yrAgahSPNWvRyhJIKOUGWaqC/wpp9Q5KrG6d+